### ISSUE TITLE
There was a problem with the requested skill's response

### ISSUE THREAD

**Issue by gabed457** [alexa-samples/skill-sample-nodejs-alexa-conversations-pet-match#2]
The following issue occurred on [Module 4](https://developer.amazon.com/en-US/alexa/alexa-skills-kit/get-deeper/tutorials-code-samples/build-multi-turn-skills-with-alexa-conversations/module-4)

After cloning the github files into the code section in the console I still received the error:

 There was a problem with the requested skill's response

This was my Dialog Flow: 

User: open pet match
Alexa: Welcome to pet match. I can find the best dog for you. What temperament are you looking for in a dog?
User: i want a large family dog
Alexa: Would you prefer a high energy dog or a low energy dog?
User: low
Alexa: There was a problem with the requested skill's response

Here's the input & output JSON respectively:

`
{
	"version": "1.0",
	"session": {
		"new": false,
		"sessionId": "amzn1.echo-api.session.d0768f2a-cec5-4a03-b573-751431a79071",
		"application": {
			"applicationId": "amzn1.ask.skill.d75cecfb-cbcf-4270-8d5b-5aa17d59807d"
		},
		"user": {
			"userId": "amzn1.ask.account.AFS276ZIYIXDKTOHE6SQVCJYI43SEDSF6IY7ZMFTUIFJRECVQMBHGFNOARDXDK3QYJ5RSRFCZ7YIN3DHEDKX4RJ5CM4GDE6N3K3PDZF7QDIP6ZTR7LGVJXBXYLZQ7Q5BFRJMDKWZISYYQBGMNYGUTHMZRDK54SLKSB7LJZKWGNNDDZ2IDJGAZ3I55QCNY5TCJ4HHVYN422UBIIQ"
		}
	},
	"context": {
		"System": {
			"application": {
				"applicationId": "amzn1.ask.skill.d75cecfb-cbcf-4270-8d5b-5aa17d59807d"
			},
			"user": {
				"userId": "amzn1.ask.account.AFS276ZIYIXDKTOHE6SQVCJYI43SEDSF6IY7ZMFTUIFJRECVQMBHGFNOARDXDK3QYJ5RSRFCZ7YIN3DHEDKX4RJ5CM4GDE6N3K3PDZF7QDIP6ZTR7LGVJXBXYLZQ7Q5BFRJMDKWZISYYQBGMNYGUTHMZRDK54SLKSB7LJZKWGNNDDZ2IDJGAZ3I55QCNY5TCJ4HHVYN422UBIIQ"
			},
			"device": {
				"deviceId": "amzn1.ask.device.AGV6MJBNYEU4RM45O76X5ZMU2EUCPU3IYGHPLV4LBQJTIMFRSMTVKL6FBCX5AFDJ3CTUXAR3HXVWDKRY5B5XIUMLJLJ6ORRD3STB6V4DCNFZ7NUVKMM2ZS7PLWTRV7IRG2GGVJKANBZU4JTG4BASILXIJ2HJQEYKQROQJKHXY5S4FV6EBJYE2",
				"supportedInterfaces": {
					"Alexa.Presentation.APL": {
						"runtime": {
							"maxVersion": "1.4"
						}
					}
				}
			},
			"apiEndpoint": "https://api.amazonalexa.com",
			"apiAccessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjEifQ.eyJhdWQiOiJodHRwczovL2FwaS5hbWF6b25hbGV4YS5jb20iLCJpc3MiOiJBbGV4YVNraWxsS2l0Iiwic3ViIjoiYW16bjEuYXNrLnNraWxsLmQ3NWNlY2ZiLWNiY2YtNDI3MC04ZDViLTVhYTE3ZDU5ODA3ZCIsImV4cCI6MTU5NjUyMjQ4NiwiaWF0IjoxNTk2NTIyMTg2LCJuYmYiOjE1OTY1MjIxODYsInByaXZhdGVDbGFpbXMiOnsiY29udGV4dCI6IkFBQUFBQUFBQUFBaTl6WjMxRjhlcFB4cGJVZnNmVWg5S3dFQUFBQUFBQUNTcDVjNjZOOHR3M2s3eXFTYXIySVhzTVR6V0NhMi82U1RCVTdsVkRudktDWUZNbGNUdHM4N051Y2R2L1JrbzBicnV0ZUhHemgxM0RiTCtvRWlpR1VYYTNQMFZNYUpPOG12Q0VSaXJEU0tjdldJSmUrVU1Wd2lURmZDMnY0ck9IUnU0Z2YwczVSK21Jd2N4ZmJ3bFYyVXhxb3E2dlE3aGZ6c0tvR1JsZ0V1UzdYaVZoTXhPNnd1RzFxaSs2OWFaTURRdEpiWnVyN0VUR2l1VHd4YkpSUTZBMnllR25mMmV2TEx0YVVqQ2RsZ3lVVjBwOWZEQlNZaGZ6N0czcUZQK2Z6eStGeDUwTUV0Y1krc1ZQWlcrTGd2L2RjWEZNQjlWSnBveFkvNlpEQXNGTzhWQkROVytsOGtySG5ZeVFEZUxVN21EYlFJV3IvWVcwcHFWSVdab3dhMExyR0JSNmVvMDZCZnR4QWpDZzRnaTFUZVlWRlh5ckhPN0Y3N2tObnJ6ejVCQk12MkxjZ3JCSjBZQ0E9PSIsImNvbnNlbnRUb2tlbiI6bnVsbCwiZGV2aWNlSWQiOiJhbXpuMS5hc2suZGV2aWNlLkFHVjZNSkJOWUVVNFJNNDVPNzZYNVpNVTJFVUNQVTNJWUdIUExWNExCUUpUSU1GUlNNVFZLTDZGQkNYNUFGREozQ1RVWEFSM0hYVldES1JZNUI1WElVTUxKTEo2T1JSRDNTVEI2VjREQ05GWjdOVVZLTU0yWlM3UExXVFJWN0lSRzJHR1ZKS0FOQlpVNEpURzRCQVNJTFhJSjJISlFFWUtRUk9RSktIWFk1UzRGVjZFQkpZRTIiLCJ1c2VySWQiOiJhbXpuMS5hc2suYWNjb3VudC5BRlMyNzZaSVlJWERLVE9IRTZTUVZDSllJNDNTRURTRjZJWTdaTUZUVUlGSlJFQ1ZRTUJIR0ZOT0FSRFhESzNRWUo1UlNSRkNaN1lJTjNESEVES1g0Uko1Q000R0RFNk4zSzNQRFpGN1FESVA2WlRSN0xHVkpYQlhZTFpRN1E1QkZSSk1ES1daSVNZWVFCR01OWUdVVEhNWlJESzU0U0xLU0I3TEpaS1dHTk5ERFoySURKR0FaM0k1NVFDTlk1VENKNEhIVllONDIyVUJJSVEifX0.QX7PYXEQBKmzDLck3sf8boguwt9BdTUCvVEDAgMVfaojFvfZ2Yi1WGdj5hwV9Ws27RtEd9VjpbIjmUTE45ZW16vTLkYGP2k5WyK8tnLztDQQw67ZDE6yeV8YXQRR93cMhA0N0bcR7dtOARZ6xINgWSxWdXtZqsaRZkaZsZNEv_2IV_qrka1XpvGPSrEuLpt8oRihiSp9lXilu7vYowBvG4UuToqDElI1xhv33g5__0I79nfBTtPe1gh-8YyahF4e258wMXkosvrUuWMMrFyO5c5VhlH83bEL87WqI5DPp7_gH4A8UAJJYqb6-FCmi9JBuqd4rv4pdtuMeksilH0Q6Q"
		},
		"Viewport": {
			"experiences": [
				{
					"arcMinuteWidth": 246,
					"arcMinuteHeight": 144,
					"canRotate": false,
					"canResize": false
				}
			],
			"mode": "HUB",
			"shape": "RECTANGLE",
			"pixelWidth": 1024,
			"pixelHeight": 600,
			"dpi": 160,
			"currentPixelWidth": 1024,
			"currentPixelHeight": 600,
			"touch": [
				"SINGLE"
			],
			"keyboard": null,
			"video": {
				"codecs": [
					"H_264_42",
					"H_264_41"
				]
			}
		},
		"Viewports": [
			{
				"type": "APL",
				"id": "main",
				"shape": "RECTANGLE",
				"dpi": 160,
				"presentationType": "STANDARD",
				"canRotate": false,
				"configuration": {
					"current": {
						"mode": "HUB",
						"video": {
							"codecs": [
								"H_264_42",
								"H_264_41"
							]
						},
						"size": {
							"type": "DISCRETE",
							"pixelWidth": 1024,
							"pixelHeight": 600
						}
					}
				}
			}
		]
	},
	"request": {
		"type": "Dialog.API.Invoked",
		"requestId": "amzn1.echo-api.request.c901d904-ef3c-435a-9b42-de73f6f0dc10",
		"timestamp": "2020-08-04T06:23:07Z",
		"locale": "en_US",
		"apiRequest": {
			"name": "getRecommendation",
			"arguments": {
				"size": "large",
				"temperament": "family",
				"energy": "low"
			},
			"slots": {
				"size": {
					"type": "Simple",
					"value": "large",
					"resolutions": {
						"resolutionsPerAuthority": [
							{
								"authority": "amzn1.er-authority.echo-sdk.amzn1.ask.skill.d75cecfb-cbcf-4270-8d5b-5aa17d59807d.size",
								"status": {
									"code": "ER_SUCCESS_MATCH"
								},
								"values": [
									{
										"value": {
											"name": "large",
											"id": "afacdb0a401ccdf6b48551bbc00e8a74"
										}
									}
								]
							}
						]
					}
				},
				"temperament": {
					"type": "Simple",
					"value": "family",
					"resolutions": {
						"resolutionsPerAuthority": [
							{
								"authority": "amzn1.er-authority.echo-sdk.amzn1.ask.skill.d75cecfb-cbcf-4270-8d5b-5aa17d59807d.temperament",
								"status": {
									"code": "ER_SUCCESS_MATCH"
								},
								"values": [
									{
										"value": {
											"name": "family",
											"id": "0d3fda0bdbb9d619e09cdf3eecba7999"
										}
									}
								]
							}
						]
					}
				},
				"energy": {
					"type": "Simple",
					"value": "low",
					"resolutions": {
						"resolutionsPerAuthority": [
							{
								"authority": "amzn1.er-authority.echo-sdk.amzn1.ask.skill.d75cecfb-cbcf-4270-8d5b-5aa17d59807d.energy",
								"status": {
									"code": "ER_SUCCESS_MATCH"
								},
								"values": [
									{
										"value": {
											"name": "low",
											"id": "53cced8d281a1a0ace3cb6594daaa4f7"
										}
									}
								]
							}
						]
					}
				}
			}
		}
	}
}
`

`
{
	"body": {
		"version": "1.0",
		"response": {
			"outputSpeech": {
				"type": "SSML",
				"ssml": "<speak>Sorry, I had trouble doing what you asked. Please try again.</speak>"
			},
			"reprompt": {
				"outputSpeech": {
					"type": "SSML",
					"ssml": "<speak>Sorry, I had trouble doing what you asked. Please try again.</speak>"
				}
			},
			"shouldEndSession": false
		},
		"userAgent": "ask-node/2.8.0 Node/v10.21.0",
		"sessionAttributes": {}
	}
}
`

**Comment by aszk** [comment]
Could you [contact us](alexa.design/contactus) if you still have the issue? I'd also want you to make sure if this can be reproduced by the final version.
